version: '3'

vars:
  APP: amprobe
  SERVER: ./cmd/{{.APP}}
  STAMP:
    sh: date +%s
  VERSION:
    sh: cat VERSION
  GIT_HASH:
    sh: git rev-parse --short=8 HEAD
  GIT_BRANCH:
    sh: git rev-parse --abbrev-ref HEAD
  IMAGE: amuluze/amprobe
  TAG: '{{.VERSION}}'
  CONFIG_FILE: '{{.TASKFILE_DIR}}/configs/config.toml'
  MODEL_FILE: '{{.TASKFILE_DIR}}/configs/model.conf'
  DEV_CONFIG_FILE: '{{.TASKFILE_DIR}}/configs/config.dev.toml'

tasks:
  dev:
    desc: Run amprobe in development mode
    cmds:
      - go run {{.SERVER}}/main.go run -c {{.DEV_CONFIG_FILE}} -m {{.MODEL_FILE}}

  wire:
    desc: Generate Wire dependency injection code
    cmds:
      - wire ./service/

  test:
    desc: Run tests with race detector
    cmds:
      - go test -race -count=1 ./...

  bin:
    desc: Build amprobe binary
    cmds:
      - go build -ldflags "-w -s -X main.BuildStamp={{.STAMP}} -X main.GitHash={{.GIT_HASH}} -X main.GitBranch={{.GIT_BRANCH}} -X main.Version={{.VERSION}}" -o {{.APP}} {{.SERVER}}

  amd64:
    desc: Build linux/amd64 Docker image
    deps:
      - bin
    cmds:
      - docker buildx build --platform linux/amd64 -t {{.IMAGE}}:{{.TAG}} -o type=docker .

  arm64:
    desc: Build linux/arm64 Docker image
    deps:
      - bin
    cmds:
      - docker buildx build --platform linux/arm64 -t {{.IMAGE}}:{{.TAG}} -o type=docker .

  build:
    desc: Build and push multi-arch Docker image
    cmds:
      - docker buildx build --platform linux/amd64,linux/arm64 -t {{.IMAGE}}:{{.TAG}} . --push
