services:
  amprobe:
    build:
      context: .
      dockerfile: amprobe/Dockerfile
    image: amprobe:local
    container_name: amprobe
    restart: unless-stopped
    ports:
      - "1443:80"
    volumes:
      - ./deploy/logs:/app/logs
