version: '3'

includes:
  beacon:
    taskfile: ./beacon/Taskfile.yml
    dir: ./beacon
  beacon-web:
    taskfile: ./beacon/web/Taskfile.yml
    dir: ./beacon/web
  collia:
    taskfile: ./collia/Taskfile.yml
    dir: ./collia
  website:
    taskfile: ./website/Taskfile.yml
    dir: ./website
  website-server:
    taskfile: ./website/server/Taskfile.yml
    dir: ./website/server
  website-web:
    taskfile: ./website/web/Taskfile.yml
    dir: ./website/web

tasks:
  default:
    desc: List available tasks
    cmds:
      - task --list
