version: '3'

includes:
  amprobe:
    taskfile: ./amprobe/Taskfile.yml
    dir: ./amprobe
  amprobe-web:
    taskfile: ./amprobe/web/Taskfile.yml
    dir: ./amprobe/web
  collia:
    taskfile: ./collia/Taskfile.yml
    dir: ./collia
  website:
    taskfile: ./website/Taskfile.yml
    dir: ./website
  website-server:
    taskfile: ./website/server/Taskfile.yml
    dir: ./website/server
  website-web:
    taskfile: ./website/web/Taskfile.yml
    dir: ./website/web

tasks:
  default:
    desc: List available tasks
    cmds:
      - task --list
