version: '3'

vars:
  APP: beacon
  SERVER: ./cmd/{{.APP}}
  VERSION:
    sh: cat VERSION
  REGISTRY: registry.cn-hangzhou.aliyuncs.com
  IMAGE: '{{.REGISTRY}}/amuluze/beacon'
  TAG: '{{.VERSION}}'
  DEV_CONFIG_FILE: '{{.TASKFILE_DIR}}/configs/config.dev.toml'
  MODEL_FILE: '{{.TASKFILE_DIR}}/configs/model.conf'

tasks:
  default:
    desc: List available tasks
    cmds:
      - task --list

  dev:
    desc: Run beacon with development config
    cmds:
      - go run {{.SERVER}}/main.go run -c {{.DEV_CONFIG_FILE}} -m {{.MODEL_FILE}}

  wire:
    desc: Generate Wire injector code
    cmds:
      - wire ./service/

  bin:
    desc: Build local beacon binary
    vars:
      STAMP:
        sh: date +%s
      GIT_HASH:
        sh: git rev-parse --short=8 HEAD
      GIT_BRANCH:
        sh: git rev-parse --abbrev-ref HEAD
    cmds:
      - go build -ldflags "-w -s -X main.BuildStamp={{.STAMP}} -X main.GitHash={{.GIT_HASH}} -X main.GitBranch={{.GIT_BRANCH}} -X main.Version={{.VERSION}}" -o {{.APP}} {{.SERVER}}

  amd64:
    desc: Build linux/amd64 Docker image into local Docker
    deps:
      - bin
    cmds:
      - docker buildx build --platform linux/amd64 -t {{.IMAGE}}:{{.TAG}} -o type=docker .

  arm64:
    desc: Build linux/arm64 Docker image into local Docker
    deps:
      - bin
    cmds:
      - docker buildx build --platform linux/arm64 -t {{.IMAGE}}:{{.TAG}} -o type=docker .

  build:
    desc: Build and push multi-platform Docker image
    cmds:
      - docker buildx build --platform linux/amd64,linux/arm64 -t {{.IMAGE}}:{{.TAG}} . --push
