// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package service

import (
	"server/service/model"
	"server/service/statistics/api"
	"server/service/statistics/repository"
	"server/service/statistics/service"
)

// Injectors from wire.go:

func BuildInjector(configFile string) (*Injector, func(), error) {
	config, err := NewConfig(configFile)
	if err != nil {
		return nil, nil, err
	}
	models := model.NewModels()
	db, dbCleanup, err := NewDB(config, models)
	if err != nil {
		return nil, nil, err
	}
	statisticsRepository := repository.NewStatisticsRepository(db)
	statisticsService := service.NewStatisticsService(statisticsRepository)
	statisticsAPI := api.NewStatisticsAPI(statisticsService)
	router := &Router{
		config:        config,
		statisticsAPI: statisticsAPI,
	}
	app := NewFiberApp(config, router)
	logger := NewLogger(config)
	injector, err := NewInjector(app, router, config, logger)
	if err != nil {
		dbCleanup()
		return nil, nil, err
	}
	return injector, func() {
		dbCleanup()
	}, nil
}
