// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package service

import (
	"collia/service/model"
)

// Injectors from wire.go:

func BuildInjector(configFile string, prefix Prefix, version Version) (*Injector, func(), error) {
	config, err := NewConfig(configFile, prefix)
	if err != nil {
		return nil, nil, err
	}
	timedTask := NewTimedTask(config)
	models := model.NewModels()
	db, err := NewDB(config, models)
	if err != nil {
		return nil, nil, err
	}
	server, err := NewRPCServer(config, db, version)
	if err != nil {
		return nil, nil, err
	}
	logger := NewLogger(config)
	injector, err := NewInjector(config, timedTask, server, logger)
	if err != nil {
		return nil, nil, err
	}
	return injector, func() {
	}, nil
}
