// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.1
// 	protoc        v4.22.2
// source: rpc/proto/tunnel.proto

package tunnel

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FrameType distinguishes frame roles in the tunnel protocol.
type FrameType int32

const (
	FrameType_FRAME_UNSPECIFIED FrameType = 0
	FrameType_FRAME_REQUEST     FrameType = 1 // Server → Agent: RPC call request
	FrameType_FRAME_REPLY       FrameType = 2 // Agent → Server: single response
	FrameType_FRAME_STREAM_DATA FrameType = 3 // Agent → Server: streaming data chunk
	FrameType_FRAME_STREAM_END  FrameType = 4 // Agent → Server: stream complete
	FrameType_FRAME_HEARTBEAT   FrameType = 5 // Agent → Server: keep-alive ping
	FrameType_FRAME_REGISTER    FrameType = 6 // Agent → Server: registration
)

// Enum value maps for FrameType.
var (
	FrameType_name = map[int32]string{
		0: "FRAME_UNSPECIFIED",
		1: "FRAME_REQUEST",
		2: "FRAME_REPLY",
		3: "FRAME_STREAM_DATA",
		4: "FRAME_STREAM_END",
		5: "FRAME_HEARTBEAT",
		6: "FRAME_REGISTER",
	}
	FrameType_value = map[string]int32{
		"FRAME_UNSPECIFIED": 0,
		"FRAME_REQUEST":     1,
		"FRAME_REPLY":       2,
		"FRAME_STREAM_DATA": 3,
		"FRAME_STREAM_END":  4,
		"FRAME_HEARTBEAT":   5,
		"FRAME_REGISTER":    6,
	}
)

func (x FrameType) Enum() *FrameType {
	p := new(FrameType)
	*p = x
	return p
}

func (x FrameType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FrameType) Descriptor() protoreflect.EnumDescriptor {
	return file_rpc_proto_tunnel_proto_enumTypes[0].Descriptor()
}

func (FrameType) Type() protoreflect.EnumType {
	return &file_rpc_proto_tunnel_proto_enumTypes[0]
}

func (x FrameType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FrameType.Descriptor instead.
func (FrameType) EnumDescriptor() ([]byte, []int) {
	return file_rpc_proto_tunnel_proto_rawDescGZIP(), []int{0}
}

// Frame is a single message exchanged over the tunnel.
type Frame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                                       // correlation ID, matches request with response
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`                                               // RPC method name, e.g. "ContainerCreate"
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`                                             // JSON-encoded args (request) or reply (response)
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`                                                 // non-empty if the RPC returned an error
	Eos           bool                   `protobuf:"varint,5,opt,name=eos,proto3" json:"eos,omitempty"`                                                    // end-of-stream marker (deprecated, use frame_type)
	FrameType     FrameType              `protobuf:"varint,6,opt,name=frame_type,json=frameType,proto3,enum=tunnel.FrameType" json:"frame_type,omitempty"` // frame role
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Frame) Reset() {
	*x = Frame{}
	mi := &file_rpc_proto_tunnel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Frame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Frame) ProtoMessage() {}

func (x *Frame) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_tunnel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Frame.ProtoReflect.Descriptor instead.
func (*Frame) Descriptor() ([]byte, []int) {
	return file_rpc_proto_tunnel_proto_rawDescGZIP(), []int{0}
}

func (x *Frame) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Frame) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *Frame) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Frame) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *Frame) GetEos() bool {
	if x != nil {
		return x.Eos
	}
	return false
}

func (x *Frame) GetFrameType() FrameType {
	if x != nil {
		return x.FrameType
	}
	return FrameType_FRAME_UNSPECIFIED
}

var File_rpc_proto_tunnel_proto protoreflect.FileDescriptor

var file_rpc_proto_tunnel_proto_rawDesc = []byte{
	0x0a, 0x16, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x75, 0x6e, 0x6e,
	0x65, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x74, 0x75, 0x6e, 0x6e, 0x65, 0x6c,
	0x22, 0xa3, 0x01, 0x0a, 0x05, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65,
	0x74, 0x68, 0x6f, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x65, 0x74, 0x68,
	0x6f, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x14, 0x0a, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x6f, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x03, 0x65, 0x6f, 0x73, 0x12, 0x30, 0x0a, 0x0a, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x5f, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x74, 0x75, 0x6e, 0x6e, 0x65,
	0x6c, 0x2e, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x09, 0x66, 0x72, 0x61,
	0x6d, 0x65, 0x54, 0x79, 0x70, 0x65, 0x2a, 0x9c, 0x01, 0x0a, 0x09, 0x46, 0x72, 0x61, 0x6d, 0x65,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x15, 0x0a, 0x11, 0x46, 0x52, 0x41, 0x4d, 0x45, 0x5f, 0x55, 0x4e,
	0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x11, 0x0a, 0x0d, 0x46,
	0x52, 0x41, 0x4d, 0x45, 0x5f, 0x52, 0x45, 0x51, 0x55, 0x45, 0x53, 0x54, 0x10, 0x01, 0x12, 0x0f,
	0x0a, 0x0b, 0x46, 0x52, 0x41, 0x4d, 0x45, 0x5f, 0x52, 0x45, 0x50, 0x4c, 0x59, 0x10, 0x02, 0x12,
	0x15, 0x0a, 0x11, 0x46, 0x52, 0x41, 0x4d, 0x45, 0x5f, 0x53, 0x54, 0x52, 0x45, 0x41, 0x4d, 0x5f,
	0x44, 0x41, 0x54, 0x41, 0x10, 0x03, 0x12, 0x14, 0x0a, 0x10, 0x46, 0x52, 0x41, 0x4d, 0x45, 0x5f,
	0x53, 0x54, 0x52, 0x45, 0x41, 0x4d, 0x5f, 0x45, 0x4e, 0x44, 0x10, 0x04, 0x12, 0x13, 0x0a, 0x0f,
	0x46, 0x52, 0x41, 0x4d, 0x45, 0x5f, 0x48, 0x45, 0x41, 0x52, 0x54, 0x42, 0x45, 0x41, 0x54, 0x10,
	0x05, 0x12, 0x12, 0x0a, 0x0e, 0x46, 0x52, 0x41, 0x4d, 0x45, 0x5f, 0x52, 0x45, 0x47, 0x49, 0x53,
	0x54, 0x45, 0x52, 0x10, 0x06, 0x32, 0x3b, 0x0a, 0x0d, 0x52, 0x65, 0x76, 0x65, 0x72, 0x73, 0x65,
	0x54, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x2a, 0x0a, 0x06, 0x54, 0x75, 0x6e, 0x6e, 0x65, 0x6c,
	0x12, 0x0d, 0x2e, 0x74, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x2e, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x1a,
	0x0d, 0x2e, 0x74, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x2e, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x28, 0x01,
	0x30, 0x01, 0x42, 0x13, 0x5a, 0x11, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x72, 0x70, 0x63,
	0x2f, 0x74, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_proto_tunnel_proto_rawDescOnce sync.Once
	file_rpc_proto_tunnel_proto_rawDescData = file_rpc_proto_tunnel_proto_rawDesc
)

func file_rpc_proto_tunnel_proto_rawDescGZIP() []byte {
	file_rpc_proto_tunnel_proto_rawDescOnce.Do(func() {
		file_rpc_proto_tunnel_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_proto_tunnel_proto_rawDescData)
	})
	return file_rpc_proto_tunnel_proto_rawDescData
}

var file_rpc_proto_tunnel_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_rpc_proto_tunnel_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_rpc_proto_tunnel_proto_goTypes = []any{
	(FrameType)(0), // 0: tunnel.FrameType
	(*Frame)(nil),  // 1: tunnel.Frame
}
var file_rpc_proto_tunnel_proto_depIdxs = []int32{
	0, // 0: tunnel.Frame.frame_type:type_name -> tunnel.FrameType
	1, // 1: tunnel.ReverseTunnel.Tunnel:input_type -> tunnel.Frame
	1, // 2: tunnel.ReverseTunnel.Tunnel:output_type -> tunnel.Frame
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rpc_proto_tunnel_proto_init() }
func file_rpc_proto_tunnel_proto_init() {
	if File_rpc_proto_tunnel_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_proto_tunnel_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_proto_tunnel_proto_goTypes,
		DependencyIndexes: file_rpc_proto_tunnel_proto_depIdxs,
		EnumInfos:         file_rpc_proto_tunnel_proto_enumTypes,
		MessageInfos:      file_rpc_proto_tunnel_proto_msgTypes,
	}.Build()
	File_rpc_proto_tunnel_proto = out.File
	file_rpc_proto_tunnel_proto_rawDesc = nil
	file_rpc_proto_tunnel_proto_goTypes = nil
	file_rpc_proto_tunnel_proto_depIdxs = nil
}
