/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description Returns HTTP 200 if the process is running. No authentication required.
         */
        get: operations["liveness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness probe
         * @description Returns HTTP 200 when all dependencies (DB, reverse-tunnel) are healthy; HTTP 503 when DB ping reports an error.
         */
        get: operations["readiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ws": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * WebSocket upgrade for terminal channel
         * @description Upgrade to WebSocket; rejects plain HTTP with 426.
         */
        get: operations["wsTerminal"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ws/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** WebSocket upgrade for log streaming */
        get: operations["wsLogStream"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/index/index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Hello-world sanity endpoint */
        get: operations["hello"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * User login
         * @description Authenticate with username and password. Returns JWT access and refresh tokens. Rate-limited to 10 req/min/IP.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** User logout */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/pass_update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Update password */
        post: operations["passUpdate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/token_update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Update access token via refresh token
         * @description Used by the web client interceptor (see web/src/api/index.ts) when a
         *     401 response is observed. Returns 400 when the refresh token is invalid;
         *     the client treats that as a hard logout.
         */
        post: operations["tokenUpdate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/user_info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current user info + permissions */
        get: operations["userInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agent/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List known Agents
         * @description Returns the list of Agents known to the Server with their lifecycle state.
         */
        get: operations["listAgents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/user/user_query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查询用户 */
        get: operations["userQuery"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/user/user_create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 创建用户 */
        post: operations["userCreate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/user/user_update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 更新用户 */
        post: operations["userUpdate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/user/user_delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 删除用户 */
        post: operations["userDelete"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/role/role_query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查询角色 */
        get: operations["roleQuery"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/role/role_create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 创建角色 */
        post: operations["roleCreate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/role/role_update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 更新角色 */
        post: operations["roleUpdate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/role/role_delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 删除角色 */
        post: operations["roleDelete"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/resource/resource_query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查询资源 */
        get: operations["resourceQuery"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/container/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取 Docker 版本信息 */
        get: operations["containerVersion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/container/containers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取容器列表
         * @description Returns the latest container list for the selected Agent.
         */
        get: operations["containerList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/container/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取容器资源使用情况 */
        get: operations["containerUsage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/container/container_create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 创建容器 */
        post: operations["containerCreate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/container/container_start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 启动容器 */
        post: operations["containerStart"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/container/container_stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 停止容器 */
        post: operations["containerStop"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/container/container_restart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 重启容器 */
        post: operations["containerRestart"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/container/container_remove": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 删除容器 */
        post: operations["containerRemove"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/container/images": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取镜像列表 */
        get: operations["imageList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/container/image_remove": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 删除镜像 */
        post: operations["imageRemove"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/container/images_prune": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 清理虚悬镜像 */
        post: operations["imagesPrune"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/container/image_pull": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 拉取镜像 */
        post: operations["imagePull"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/container/image_import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 导入镜像 */
        post: operations["imageImport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/container/image_export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 导出镜像 */
        post: operations["imageExport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/container/network_create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 创建网络 */
        post: operations["networkCreate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/container/network_delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 删除网络 */
        post: operations["networkDelete"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/container/networks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取网络列表 */
        get: operations["networkList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/container/get_docker_registry_mirrors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取 Docker 镜像设置 */
        get: operations["getDockerRegistryMirrors"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/container/set_docker_registry_mirrors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 更新 Docker 镜像设置 */
        post: operations["setDockerRegistryMirrors"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/host/install": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取 Collia 安装脚本
         * @description Returns the bash installation script for the target node.
         */
        get: operations["agentInstallScript"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/host/install/package": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 下载 Collia 安装包 */
        get: operations["agentInstallPackage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/host/install/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 下载 Collia 配置 */
        get: operations["agentInstallConfig"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/host/install/certs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 下载 Collia 证书 */
        get: operations["agentInstallCerts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/host/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Agent monitoring report
         * @description Receives a monitoring data batch from an Agent and persists it atomically.
         *     Must include `X-Agent-ID` or `agent_id` in the request. Must include
         *     `X-Install-Token` or `token` if configured. Rate-limited to 60 req/min
         *     per Agent ID / IP.
         */
        post: operations["report"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/host/host_info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get host information
         * @description Returns the latest host info for the selected Agent.
         */
        get: operations["hostInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/host/cpu_info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取 CPU 信息 */
        get: operations["cpuInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/host/mem_info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取内存信息 */
        get: operations["memInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/host/disk_info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取磁盘信息 */
        get: operations["diskInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/host/cpu_trending": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取 CPU 使用率 */
        get: operations["cpuUsage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/host/mem_trending": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取内存使用率 */
        get: operations["memUsage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/host/disk_trending": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取磁盘使用率 */
        get: operations["diskUsage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/host/net_trending": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取网络使用率 */
        get: operations["netUsage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/host/file_search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 文件搜索 */
        get: operations["filesSearch"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/host/file_upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 文件上传 */
        post: operations["fileUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/host/file_download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 文件下载 */
        post: operations["fileDownload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/host/file_delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 删除文件 */
        post: operations["fileDelete"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/host/file_create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 创建文件 */
        post: operations["fileCreate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/host/folder_create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 创建文件夹 */
        post: operations["folderCreate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/host/get_dns_settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取 DNS 设置 */
        get: operations["getDnsSettings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/host/set_dns_settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 更新 DNS 设置 */
        post: operations["setDnsSettings"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/host/get_system_time": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取系统时间 */
        get: operations["getSystemTime"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/host/set_system_time": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 更新系统时间 */
        post: operations["setSystemTime"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/host/get_system_timezone_list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取系统时区列表 */
        get: operations["getSystemTimeZoneList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/host/get_system_timezone": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取系统时区 */
        get: operations["getSystemTimeZone"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/host/set_system_timezone": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 更新系统时区 */
        post: operations["setSystemTimeZone"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/host/reboot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 重启系统 */
        post: operations["reboot"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/host/shutdown": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 关闭系统 */
        post: operations["shutdown"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audit/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取审计日志 */
        get: operations["auditQuery"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/mail/mail_create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 创建邮件告警配置 */
        post: operations["mailCreate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/mail/mail_delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 删除邮件告警配置 */
        post: operations["mailDelete"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/mail/mail_update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 更新邮件告警配置 */
        post: operations["mailUpdate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/mail/mail_query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查询邮件告警配置 */
        get: operations["mailQuery"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/mail/mail_test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 测试邮件告警 */
        post: operations["mailTest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alarm/alarm_update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 更新告警阈值 */
        post: operations["alarmUpdate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alarm/alarm_query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查询告警阈值 */
        get: operations["alarmQuery"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponse: {
            /** @example alive */
            status?: string;
            /** @example 120.5 */
            uptime?: number;
            /** Format: date-time */
            timestamp?: string;
        };
        /**
         * @description Derived from the Agent-side collection timestamp in each monitoring row.
         *     `stale` and `degraded` are both true when the row's age exceeds the
         *     `freshnessStaleAfter` constant (2 minutes by default).
         */
        Freshness: {
            /**
             * Format: int64
             * @description Unix epoch of the original collection.
             */
            collected_at?: number;
            age_seconds?: number;
            stale?: boolean;
            degraded?: boolean;
        };
        /** @description Single point on the CPU / memory time series. */
        UsagePoint: {
            /**
             * Format: int64
             * @description Unix epoch
             */
            timestamp?: number;
            /** Format: double */
            value?: number;
        };
        /** @description Disk usage grouped by device. */
        DiskUsage: {
            device?: string;
            data?: {
                /** Format: int64 */
                timestamp?: number;
                io_read?: number;
                io_write?: number;
            }[];
        };
        /** @description Network usage grouped by ethernet. */
        NetUsage: {
            ethernet?: string;
            data?: {
                /** Format: int64 */
                timestamp?: number;
                bytes_sent?: number;
                bytes_recv?: number;
            }[];
        };
        /**
         * @description Mirrors `common/rpc/schema.Container`. JSON omits empty fields so the
         *     optional Num/Tag fields may be missing.
         */
        Container: {
            /** Format: date-time */
            timestamp?: string;
            container_id?: string;
            name?: string;
            image?: string;
            network?: string;
            ip?: string;
            ports?: string;
            state?: string;
            uptime?: string;
            volumes?: string;
            environments?: string;
            commands?: string;
            labels?: string;
            cpu_percent?: number;
            mem_percent?: number;
            mem_usage?: number;
            mem_limit?: number;
        };
    };
    responses: never;
    parameters: {
        /**
         * @description Identifies the target Agent for control-plane endpoints. Required for
         *     any host.* or container.* path; the repository layer (see
         *     RequireAgentID in amprobe/pkg/contextx) rejects the request with
         *     HTTP 400 when missing.
         */
        XAgentID: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    liveness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server is alive */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    readiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server is ready */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Server is not ready */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    wsTerminal: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Switching protocols */
            101: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Upgrade required */
            426: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    wsLogStream: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Switching protocols */
            101: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Upgrade required */
            426: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    hello: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Plain text: hello world */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    username?: string;
                    password?: string;
                };
            };
        };
        responses: {
            /** @description Login successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Too many requests (rate limited) */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logged out */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    passUpdate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Password updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    tokenUpdate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description New token pair issued */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Refresh token invalid; client clears tokens */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    userInfo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User info payload */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listAgents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Agent list (may be empty) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    userQuery: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    userCreate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description User created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    userUpdate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    userDelete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    roleQuery: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Roles */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    roleCreate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    roleUpdate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    roleDelete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    resourceQuery: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Resources */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    containerVersion: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description Identifies the target Agent for control-plane endpoints. Required for
                 *     any host.* or container.* path; the repository layer (see
                 *     RequireAgentID in amprobe/pkg/contextx) rejects the request with
                 *     HTTP 400 when missing.
                 */
                "X-Agent-ID"?: components["parameters"]["XAgentID"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Docker version payload */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    containerList: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
            };
            header: {
                /** @description Target Agent identifier */
                "X-Agent-ID": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Container list with freshness metadata */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["Container"][];
                        freshness?: components["schemas"]["Freshness"];
                    };
                };
            };
            /** @description Missing Agent ID */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    containerUsage: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description Identifies the target Agent for control-plane endpoints. Required for
                 *     any host.* or container.* path; the repository layer (see
                 *     RequireAgentID in amprobe/pkg/contextx) rejects the request with
                 *     HTTP 400 when missing.
                 */
                "X-Agent-ID"?: components["parameters"]["XAgentID"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Aggregate usage */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    containerCreate: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description Identifies the target Agent for control-plane endpoints. Required for
                 *     any host.* or container.* path; the repository layer (see
                 *     RequireAgentID in amprobe/pkg/contextx) rejects the request with
                 *     HTTP 400 when missing.
                 */
                "X-Agent-ID"?: components["parameters"]["XAgentID"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid spec */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    containerStart: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description Identifies the target Agent for control-plane endpoints. Required for
                 *     any host.* or container.* path; the repository layer (see
                 *     RequireAgentID in amprobe/pkg/contextx) rejects the request with
                 *     HTTP 400 when missing.
                 */
                "X-Agent-ID"?: components["parameters"]["XAgentID"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Started */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    containerStop: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description Identifies the target Agent for control-plane endpoints. Required for
                 *     any host.* or container.* path; the repository layer (see
                 *     RequireAgentID in amprobe/pkg/contextx) rejects the request with
                 *     HTTP 400 when missing.
                 */
                "X-Agent-ID"?: components["parameters"]["XAgentID"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stopped */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    containerRestart: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description Identifies the target Agent for control-plane endpoints. Required for
                 *     any host.* or container.* path; the repository layer (see
                 *     RequireAgentID in amprobe/pkg/contextx) rejects the request with
                 *     HTTP 400 when missing.
                 */
                "X-Agent-ID"?: components["parameters"]["XAgentID"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Restarted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    containerRemove: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description Identifies the target Agent for control-plane endpoints. Required for
                 *     any host.* or container.* path; the repository layer (see
                 *     RequireAgentID in amprobe/pkg/contextx) rejects the request with
                 *     HTTP 400 when missing.
                 */
                "X-Agent-ID"?: components["parameters"]["XAgentID"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Removed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    imageList: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description Identifies the target Agent for control-plane endpoints. Required for
                 *     any host.* or container.* path; the repository layer (see
                 *     RequireAgentID in amprobe/pkg/contextx) rejects the request with
                 *     HTTP 400 when missing.
                 */
                "X-Agent-ID"?: components["parameters"]["XAgentID"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Image list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    imageRemove: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description Identifies the target Agent for control-plane endpoints. Required for
                 *     any host.* or container.* path; the repository layer (see
                 *     RequireAgentID in amprobe/pkg/contextx) rejects the request with
                 *     HTTP 400 when missing.
                 */
                "X-Agent-ID"?: components["parameters"]["XAgentID"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Removed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    imagesPrune: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description Identifies the target Agent for control-plane endpoints. Required for
                 *     any host.* or container.* path; the repository layer (see
                 *     RequireAgentID in amprobe/pkg/contextx) rejects the request with
                 *     HTTP 400 when missing.
                 */
                "X-Agent-ID"?: components["parameters"]["XAgentID"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pruned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    imagePull: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description Identifies the target Agent for control-plane endpoints. Required for
                 *     any host.* or container.* path; the repository layer (see
                 *     RequireAgentID in amprobe/pkg/contextx) rejects the request with
                 *     HTTP 400 when missing.
                 */
                "X-Agent-ID"?: components["parameters"]["XAgentID"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Pulled */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    imageImport: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description Identifies the target Agent for control-plane endpoints. Required for
                 *     any host.* or container.* path; the repository layer (see
                 *     RequireAgentID in amprobe/pkg/contextx) rejects the request with
                 *     HTTP 400 when missing.
                 */
                "X-Agent-ID"?: components["parameters"]["XAgentID"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Imported */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    imageExport: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description Identifies the target Agent for control-plane endpoints. Required for
                 *     any host.* or container.* path; the repository layer (see
                 *     RequireAgentID in amprobe/pkg/contextx) rejects the request with
                 *     HTTP 400 when missing.
                 */
                "X-Agent-ID"?: components["parameters"]["XAgentID"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Exported */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    networkCreate: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description Identifies the target Agent for control-plane endpoints. Required for
                 *     any host.* or container.* path; the repository layer (see
                 *     RequireAgentID in amprobe/pkg/contextx) rejects the request with
                 *     HTTP 400 when missing.
                 */
                "X-Agent-ID"?: components["parameters"]["XAgentID"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    networkDelete: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description Identifies the target Agent for control-plane endpoints. Required for
                 *     any host.* or container.* path; the repository layer (see
                 *     RequireAgentID in amprobe/pkg/contextx) rejects the request with
                 *     HTTP 400 when missing.
                 */
                "X-Agent-ID"?: components["parameters"]["XAgentID"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    networkList: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description Identifies the target Agent for control-plane endpoints. Required for
                 *     any host.* or container.* path; the repository layer (see
                 *     RequireAgentID in amprobe/pkg/contextx) rejects the request with
                 *     HTTP 400 when missing.
                 */
                "X-Agent-ID"?: components["parameters"]["XAgentID"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Network list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getDockerRegistryMirrors: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description Identifies the target Agent for control-plane endpoints. Required for
                 *     any host.* or container.* path; the repository layer (see
                 *     RequireAgentID in amprobe/pkg/contextx) rejects the request with
                 *     HTTP 400 when missing.
                 */
                "X-Agent-ID"?: components["parameters"]["XAgentID"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Mirror config */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    setDockerRegistryMirrors: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description Identifies the target Agent for control-plane endpoints. Required for
                 *     any host.* or container.* path; the repository layer (see
                 *     RequireAgentID in amprobe/pkg/contextx) rejects the request with
                 *     HTTP 400 when missing.
                 */
                "X-Agent-ID"?: components["parameters"]["XAgentID"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    agentInstallScript: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bash script */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    agentInstallPackage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Binary archive */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    agentInstallConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Agent config */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    agentInstallCerts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description TLS material */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    report: {
        parameters: {
            query?: {
                agent_id?: string;
            };
            header?: {
                /**
                 * @description Identifies the target Agent for control-plane endpoints. Required for
                 *     any host.* or container.* path; the repository layer (see
                 *     RequireAgentID in amprobe/pkg/contextx) rejects the request with
                 *     HTTP 400 when missing.
                 */
                "X-Agent-ID"?: components["parameters"]["XAgentID"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": Record<string, never>;
            };
        };
        responses: {
            /** @description Batch stored successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing Agent ID or malformed batch */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid install token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Too many requests (rate limited) */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    hostInfo: {
        parameters: {
            query?: never;
            header: {
                /** @description Target Agent identifier */
                "X-Agent-ID": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Host info with freshness metadata */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: int64 */
                        timestamp?: number;
                        uptime?: string;
                        hostname?: string;
                        os?: string;
                        platform?: string;
                        platform_version?: string;
                        kernel_version?: string;
                        kernel_arch?: string;
                        freshness?: components["schemas"]["Freshness"];
                    };
                };
            };
            /** @description Missing Agent ID */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    cpuInfo: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description Identifies the target Agent for control-plane endpoints. Required for
                 *     any host.* or container.* path; the repository layer (see
                 *     RequireAgentID in amprobe/pkg/contextx) rejects the request with
                 *     HTTP 400 when missing.
                 */
                "X-Agent-ID"?: components["parameters"]["XAgentID"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description CPU info payload */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    memInfo: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description Identifies the target Agent for control-plane endpoints. Required for
                 *     any host.* or container.* path; the repository layer (see
                 *     RequireAgentID in amprobe/pkg/contextx) rejects the request with
                 *     HTTP 400 when missing.
                 */
                "X-Agent-ID"?: components["parameters"]["XAgentID"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Memory info payload */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    diskInfo: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description Identifies the target Agent for control-plane endpoints. Required for
                 *     any host.* or container.* path; the repository layer (see
                 *     RequireAgentID in amprobe/pkg/contextx) rejects the request with
                 *     HTTP 400 when missing.
                 */
                "X-Agent-ID"?: components["parameters"]["XAgentID"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Disk info payload */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    cpuUsage: {
        parameters: {
            query?: {
                start_time?: number;
                end_time?: number;
            };
            header?: {
                /**
                 * @description Identifies the target Agent for control-plane endpoints. Required for
                 *     any host.* or container.* path; the repository layer (see
                 *     RequireAgentID in amprobe/pkg/contextx) rejects the request with
                 *     HTTP 400 when missing.
                 */
                "X-Agent-ID"?: components["parameters"]["XAgentID"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description CPU usage time series */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["UsagePoint"][];
                    };
                };
            };
            /** @description Missing agent_id or invalid time range */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    memUsage: {
        parameters: {
            query?: {
                start_time?: number;
                end_time?: number;
            };
            header?: {
                /**
                 * @description Identifies the target Agent for control-plane endpoints. Required for
                 *     any host.* or container.* path; the repository layer (see
                 *     RequireAgentID in amprobe/pkg/contextx) rejects the request with
                 *     HTTP 400 when missing.
                 */
                "X-Agent-ID"?: components["parameters"]["XAgentID"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Memory usage time series */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["UsagePoint"][];
                    };
                };
            };
            /** @description Missing agent_id or invalid time range */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    diskUsage: {
        parameters: {
            query?: {
                start_time?: number;
                end_time?: number;
            };
            header?: {
                /**
                 * @description Identifies the target Agent for control-plane endpoints. Required for
                 *     any host.* or container.* path; the repository layer (see
                 *     RequireAgentID in amprobe/pkg/contextx) rejects the request with
                 *     HTTP 400 when missing.
                 */
                "X-Agent-ID"?: components["parameters"]["XAgentID"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Disk usage time series (per device) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        usage?: components["schemas"]["DiskUsage"][];
                    };
                };
            };
        };
    };
    netUsage: {
        parameters: {
            query?: {
                start_time?: number;
                end_time?: number;
            };
            header?: {
                /**
                 * @description Identifies the target Agent for control-plane endpoints. Required for
                 *     any host.* or container.* path; the repository layer (see
                 *     RequireAgentID in amprobe/pkg/contextx) rejects the request with
                 *     HTTP 400 when missing.
                 */
                "X-Agent-ID"?: components["parameters"]["XAgentID"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Network usage time series (per ethernet) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        usage?: components["schemas"]["NetUsage"][];
                    };
                };
            };
        };
    };
    filesSearch: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description Identifies the target Agent for control-plane endpoints. Required for
                 *     any host.* or container.* path; the repository layer (see
                 *     RequireAgentID in amprobe/pkg/contextx) rejects the request with
                 *     HTTP 400 when missing.
                 */
                "X-Agent-ID"?: components["parameters"]["XAgentID"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description File list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    fileUpload: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description Identifies the target Agent for control-plane endpoints. Required for
                 *     any host.* or container.* path; the repository layer (see
                 *     RequireAgentID in amprobe/pkg/contextx) rejects the request with
                 *     HTTP 400 when missing.
                 */
                "X-Agent-ID"?: components["parameters"]["XAgentID"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Uploaded */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    fileDownload: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description Identifies the target Agent for control-plane endpoints. Required for
                 *     any host.* or container.* path; the repository layer (see
                 *     RequireAgentID in amprobe/pkg/contextx) rejects the request with
                 *     HTTP 400 when missing.
                 */
                "X-Agent-ID"?: components["parameters"]["XAgentID"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Downloaded */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    fileDelete: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description Identifies the target Agent for control-plane endpoints. Required for
                 *     any host.* or container.* path; the repository layer (see
                 *     RequireAgentID in amprobe/pkg/contextx) rejects the request with
                 *     HTTP 400 when missing.
                 */
                "X-Agent-ID"?: components["parameters"]["XAgentID"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    fileCreate: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description Identifies the target Agent for control-plane endpoints. Required for
                 *     any host.* or container.* path; the repository layer (see
                 *     RequireAgentID in amprobe/pkg/contextx) rejects the request with
                 *     HTTP 400 when missing.
                 */
                "X-Agent-ID"?: components["parameters"]["XAgentID"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    folderCreate: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description Identifies the target Agent for control-plane endpoints. Required for
                 *     any host.* or container.* path; the repository layer (see
                 *     RequireAgentID in amprobe/pkg/contextx) rejects the request with
                 *     HTTP 400 when missing.
                 */
                "X-Agent-ID"?: components["parameters"]["XAgentID"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getDnsSettings: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description Identifies the target Agent for control-plane endpoints. Required for
                 *     any host.* or container.* path; the repository layer (see
                 *     RequireAgentID in amprobe/pkg/contextx) rejects the request with
                 *     HTTP 400 when missing.
                 */
                "X-Agent-ID"?: components["parameters"]["XAgentID"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description DNS config */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    setDnsSettings: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description Identifies the target Agent for control-plane endpoints. Required for
                 *     any host.* or container.* path; the repository layer (see
                 *     RequireAgentID in amprobe/pkg/contextx) rejects the request with
                 *     HTTP 400 when missing.
                 */
                "X-Agent-ID"?: components["parameters"]["XAgentID"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getSystemTime: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description Identifies the target Agent for control-plane endpoints. Required for
                 *     any host.* or container.* path; the repository layer (see
                 *     RequireAgentID in amprobe/pkg/contextx) rejects the request with
                 *     HTTP 400 when missing.
                 */
                "X-Agent-ID"?: components["parameters"]["XAgentID"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description System time payload */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    setSystemTime: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description Identifies the target Agent for control-plane endpoints. Required for
                 *     any host.* or container.* path; the repository layer (see
                 *     RequireAgentID in amprobe/pkg/contextx) rejects the request with
                 *     HTTP 400 when missing.
                 */
                "X-Agent-ID"?: components["parameters"]["XAgentID"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getSystemTimeZoneList: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Timezone list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getSystemTimeZone: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description Identifies the target Agent for control-plane endpoints. Required for
                 *     any host.* or container.* path; the repository layer (see
                 *     RequireAgentID in amprobe/pkg/contextx) rejects the request with
                 *     HTTP 400 when missing.
                 */
                "X-Agent-ID"?: components["parameters"]["XAgentID"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current timezone */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    setSystemTimeZone: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description Identifies the target Agent for control-plane endpoints. Required for
                 *     any host.* or container.* path; the repository layer (see
                 *     RequireAgentID in amprobe/pkg/contextx) rejects the request with
                 *     HTTP 400 when missing.
                 */
                "X-Agent-ID"?: components["parameters"]["XAgentID"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    reboot: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description Identifies the target Agent for control-plane endpoints. Required for
                 *     any host.* or container.* path; the repository layer (see
                 *     RequireAgentID in amprobe/pkg/contextx) rejects the request with
                 *     HTTP 400 when missing.
                 */
                "X-Agent-ID"?: components["parameters"]["XAgentID"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Reboot initiated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    shutdown: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description Identifies the target Agent for control-plane endpoints. Required for
                 *     any host.* or container.* path; the repository layer (see
                 *     RequireAgentID in amprobe/pkg/contextx) rejects the request with
                 *     HTTP 400 when missing.
                 */
                "X-Agent-ID"?: components["parameters"]["XAgentID"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Shutdown initiated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auditQuery: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Audit log page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    mailCreate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    mailDelete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    mailUpdate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    mailQuery: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Mail configs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    mailTest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Test sent */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    alarmUpdate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    alarmQuery: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Threshold configs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
