/**
 * @Author     : Amu
 * @Date       : 2024/11/14 00:06
 * @Description:
 */

// * 主题配置
export const themeConfig: Record<Theme.ThemeType, { [ key: string ]: string }> = {
    light: {
        // Design tokens from .pen/beacon.pen
        '--am-surface-primary': '#fbfcfe',
        '--am-surface-secondary': '#f0f2f5',
        '--am-surface-card': '#f7f8fa',
        '--am-foreground-primary': '#1f2329',
        '--am-foreground-secondary': '#4e5969',
        '--am-foreground-muted': '#86909c',
        '--am-border-primary': '#dcdfe6',
        '--am-border-subtle': '#e4e7ed',
        '--am-accent-primary': '#409eff',
        '--am-accent-success': '#569a2e',
        '--am-accent-warning': '#c28014',
        '--am-accent-danger': '#db5050',
        '--am-foreground-on-accent': '#fbfcfe',
        '--am-overlay-scrim': 'rgba(15, 23, 42, 0.38)',
        '--am-shadow-subtle': '0 1px 2px rgba(15, 23, 42, 0.04)',
        '--am-shadow-raised': '0 10px 28px rgba(15, 23, 42, 0.08)',
        '--am-topbar-height': '56px',
        '--am-statusbar-height': '44px',
        '--am-radius-sm': '4px',
        '--am-radius-md': '8px',
        '--am-spacing-xs': '4px',
        '--am-spacing-sm': '8px',
        '--am-spacing-md': '16px',
        '--am-spacing-lg': '24px',
        '--am-spacing-xl': '32px',
        '--am-font-xs': '11px',
        '--am-font-sm': '13px',
        '--am-font-md': '14px',
        '--am-font-lg': '18px',
        '--am-font-xl': '24px',
        '--am-font-2xl': '32px',
        '--el-color-primary': '#409eff',
        '--el-color-success': '#569a2e',
        '--el-color-warning': '#c28014',
        '--el-color-danger': '#db5050',
        '--el-bg-color': '#fbfcfe',
        '--el-bg-color-page': '#f0f2f5',
        '--el-fill-color-blank': '#fbfcfe',
        '--el-fill-color-light': '#f7f8fa',
        '--el-text-color-primary': '#1f2329',
        '--el-text-color-regular': '#4e5969',
        '--el-text-color-secondary': '#86909c',
        '--el-border-color': '#dcdfe6',
        '--el-border-color-light': '#e4e7ed',
        '--el-border-color-lighter': '#e4e7ed',
        '--el-table-header-bg-color': '#f0f2f5',
        '--el-table-bg-color': '#f7f8fa',
        '--el-table-tr-bg-color': '#f7f8fa',
        '--el-table-text-color': '#4e5969',
        '--el-table-header-text-color': '#1f2329',
        '--el-table-border-color': '#e4e7ed',
        '--el-menu-bg-color': '#f0f2f5',
        '--el-menu-hover-bg-color': '#e5f2ff',
        '--el-menu-active-bg-color': '#409eff',
        '--el-menu-text-color': '#4e5969',
        '--el-menu-active-color': '#fbfcfe',
        '--el-menu-hover-text-color': '#1f2329',
        '--el-menu-horizontal-sub-item-height': '50px',
        '--el-aside-logo-text-color': '#1f2329',
        '--el-aside-border-color': '#dcdfe6',
        '--el-header-logo-text-color': '#1f2329',
        '--el-header-bg-color': '#f0f2f5',
        '--el-header-text-color': '#1f2329',
        '--el-header-text-color-regular': '#4e5969',
        '--el-header-border-color': '#dcdfe6',
    },
    dark: {
        '--am-surface-primary': '#141414',
        '--am-surface-secondary': '#262727',
        '--am-surface-card': '#1d1e1f',
        '--am-foreground-primary': '#f5f7fa',
        '--am-foreground-secondary': '#cfd3dc',
        '--am-foreground-muted': '#909399',
        '--am-border-primary': '#414243',
        '--am-border-subtle': '#363637',
        '--am-accent-primary': '#409eff',
        '--am-accent-success': '#67c23a',
        '--am-accent-warning': '#e6a23c',
        '--am-accent-danger': '#f56c6c',
        '--am-foreground-on-accent': '#f5f7fa',
        '--am-overlay-scrim': 'rgba(10, 10, 10, 0.6)',
        '--am-shadow-subtle': 'none',
        '--am-shadow-raised': '0 12px 32px rgba(0, 0, 0, 0.28)',
        '--am-topbar-height': '56px',
        '--am-statusbar-height': '44px',
        '--am-radius-sm': '4px',
        '--am-radius-md': '8px',
        '--am-spacing-xs': '4px',
        '--am-spacing-sm': '8px',
        '--am-spacing-md': '16px',
        '--am-spacing-lg': '24px',
        '--am-spacing-xl': '32px',
        '--am-font-xs': '11px',
        '--am-font-sm': '13px',
        '--am-font-md': '14px',
        '--am-font-lg': '18px',
        '--am-font-xl': '24px',
        '--am-font-2xl': '32px',
        '--el-color-primary': '#409eff',
        '--el-color-success': '#67c23a',
        '--el-color-warning': '#e6a23c',
        '--el-color-danger': '#f56c6c',
        '--el-bg-color': '#141414',
        '--el-bg-color-page': '#262727',
        '--el-fill-color-blank': '#141414',
        '--el-fill-color-light': '#1d1e1f',
        '--el-text-color-primary': '#f5f7fa',
        '--el-text-color-regular': '#cfd3dc',
        '--el-text-color-secondary': '#909399',
        '--el-border-color': '#414243',
        '--el-border-color-light': '#363637',
        '--el-border-color-lighter': '#363637',
        '--el-table-header-bg-color': '#262727',
        '--el-table-bg-color': '#1d1e1f',
        '--el-table-tr-bg-color': '#1d1e1f',
        '--el-table-text-color': '#cfd3dc',
        '--el-table-header-text-color': '#f5f7fa',
        '--el-table-border-color': '#363637',
        '--el-menu-bg-color': '#1d1e1f',
        '--el-menu-hover-bg-color': '#2f3031',
        '--el-menu-active-bg-color': '#409eff',
        '--el-menu-text-color': '#dadada',
        '--el-menu-active-color': '#f5f7fa',
        '--el-menu-hover-text-color': '#f5f7fa',
        '--el-menu-horizontal-sub-item-height': '50px',
        '--el-aside-logo-text-color': '#dadada',
        '--el-aside-border-color': '#414243',
        '--el-header-logo-text-color': '#dadada',
        '--el-header-bg-color': '#262727',
        '--el-header-text-color': '#f5f7fa',
        '--el-header-text-color-regular': '#cfd3dc',
        '--el-header-border-color': '#414243',
    },
}

export const echartsThemeData = [
    {
        name: 'vintage',
        background: '#fef8ef',
        theme: [
            '#d87c7c',
            '#919e8b',
            '#d7ab82',
            '#6e7074',
            '#61a0a8',
            '#efa18d',
            '#787464',
            '#cc7e63',
            '#724e58',
            '#4b565b',
        ],
    },
    {
        name: 'dark',
        background: '#333',
        theme: [
            '#dd6b66',
            '#759aa0',
            '#e69d87',
            '#8dc1a9',
            '#ea7e53',
            '#eedd78',
            '#73a373',
            '#73b9bc',
            '#7289ab',
            '#91ca8c',
            '#f49f42',
        ],
    },
    {
        name: 'westeros',
        background: 'transparent',
        theme: ['#516b91', '#59c4e6', '#edafda', '#93b7e3', '#a5e7f0', '#cbb0e3'],
    },
    {
        name: 'essos',
        background: 'rgba(242,234,191,0.15)',
        theme: ['#893448', '#d95850', '#eb8146', '#ffb248', '#f2d643', '#ebdba4'],
    },
    {
        name: 'wonderland',
        background: 'transparent',
        theme: ['#4ea397', '#22c3aa', '#7bd9a5', '#d0648a', '#f58db2', '#f2b3c9'],
    },
    {
        name: 'walden',
        background: 'rgba(252,252,252,0)',
        theme: ['#3fb1e3', '#6be6c1', '#626c91', '#a0a7e6', '#c4ebad', '#96dee8'],
    },
    {
        name: 'chalk',
        background: '#293441',
        theme: ['#fc97af', '#87f7cf', '#f7f494', '#72ccff', '#f7c5a0', '#d4a4eb', '#d2f5a6', '#76f2f2'],
    },
    {
        name: 'infographic',
        background: 'transparent',
        theme: [
            '#C1232B',
            '#27727B',
            '#FCCE10',
            '#E87C25',
            '#B5C334',
            '#FE8463',
            '#9BCA63',
            '#FAD860',
            '#F3A43B',
            '#60C0DD',
            '#D7504B',
            '#C6E579',
            '#F4E001',
            '#F0805A',
            '#26C0C0',
        ],
    },
    {
        name: 'macarons',
        background: 'transparent',
        theme: [
            '#2ec7c9',
            '#b6a2de',
            '#5ab1ef',
            '#ffb980',
            '#d87a80',
            '#8d98b3',
            '#e5cf0d',
            '#97b552',
            '#95706d',
            '#dc69aa',
            '#07a2a4',
            '#9a7fd1',
            '#588dd5',
            '#f5994e',
            '#c05050',
            '#59678c',
            '#c9ab00',
            '#7eb00a',
            '#6f5553',
            '#c14089',
        ],
    },
    {
        name: 'roma',
        background: 'transparent',
        theme: [
            '#E01F54',
            '#001852',
            '#f5e8c8',
            '#b8d2c7',
            '#c6b38e',
            '#a4d8c2',
            '#f3d999',
            '#d3758f',
            '#dcc392',
            '#2e4783',
            '#82b6e9',
            '#ff6347',
            '#a092f1',
            '#0a915d',
            '#eaf889',
            '#6699FF',
            '#ff6666',
            '#3cb371',
            '#d5b158',
            '#38b6b6',
        ],
    },
    {
        name: 'shine',
        background: 'transparent',
        theme: ['#c12e34', '#e6b600', '#0098d9', '#2b821d', '#005eaa', '#339ca8', '#cda819', '#32a487'],
    },
    {
        name: 'purple-passion',
        background: 'rgba(91,92,110,1)',
        theme: ['#8a7ca8', '#e098c7', '#8fd3e8', '#71669e', '#cc70af', '#7cb4cc'],
    },
]
