version: '3'

tasks:
  install:
    desc: Install frontend dependencies
    cmds:
      - pnpm install

  dev:
    desc: Run frontend development server
    cmds:
      - pnpm run dev

  build:
    desc: Build frontend assets
    cmds:
      - pnpm run build

  preview:
    desc: Preview frontend production build
    cmds:
      - pnpm run preview

  ts:
    desc: Run frontend type check
    cmds:
      - pnpm run ts

  lint:
    desc: Run frontend lint
    cmds:
      - pnpm run lint

  lint:fix:
    desc: Fix frontend lint issues
    cmds:
      - pnpm run lint:fix
