version: '3'

tasks:
  default:
    desc: List available tasks
    cmds:
      - task --list

  install:
    desc: Install frontend dependencies
    cmds:
      - pnpm install

  build:
    desc: Build frontend assets
    cmds:
      - pnpm run build

  test:
    desc: Run frontend unit tests
    cmds:
      - pnpm run test

  dev:
    desc: Run frontend dev server
    cmds:
      - pnpm run dev
